# Generated by Django 5.1.2 on 2024-10-20 04:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('cover', models.BooleanField(default=False, verbose_name='Cover image')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attach_type', models.CharField(choices=[('title', 'Title'), ('text', 'Text'), ('PDF', 'PDF'), ('DOCS', 'DOCS'), ('image', 'Image'), ('link', 'Link'), ('video_file', 'Video file'), ('script', 'Script')], default='PDF', max_length=15)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('file', models.FileField(blank=True, null=True, upload_to='projects/attachs/', verbose_name='File')),
                ('image_alt', models.CharField(max_length=150, verbose_name='Image alt')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('script', models.TextField(blank=True, null=True, verbose_name='Script')),
                ('attachment_order', models.PositiveSmallIntegerField(default=1, verbose_name='Attachment order')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='projects.project', verbose_name='Project')),
            ],
            options={
                'ordering': ('attachment_order',),
            },
        ),
    ]
