# Generated by Django 5.1.2 on 2024-10-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_attachement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachement',
            name='image_alt',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Image alt'),
        ),
    ]
