# Generated by Django 5.1.2 on 2025-04-06 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachement',
            name='background_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='Enter a valid hex color code (e.g., #RRGGBB)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='attachement',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='Enter a valid hex color code (e.g., #RRGGBB)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='attachement',
            name='attach_type',
            field=models.CharField(choices=[('title', 'Title'), ('text', 'Text'), ('PDF', 'PDF'), ('DOCS', 'DOCS'), ('image', 'Image'), ('link', 'Link'), ('video_file', 'Video file'), ('script', 'Script'), ('quote', 'Quote')], default='PDF', max_length=15),
        ),
    ]
