# Generated by Django 5.1.2 on 2025-04-06 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_attachement_background_color_attachement_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachement',
            name='background_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='Enter a valid hex color code (e.g., #RRGGBB)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Backgroun color'),
        ),
    ]
