# Generated by Django 5.1.2 on 2025-04-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_attachement_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachement',
            name='url_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
