# Generated by Django 5.1.2 on 2024-11-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='url',
            field=models.URLField(default='#'),
        ),
    ]
