# Generated by Django 5.1.2 on 2025-04-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generals', '0002_alter_social_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='addition',
            field=models.TextField(blank=True, verbose_name='Additional skils'),
        ),
        migrations.AddField(
            model_name='about',
            name='addition_file',
            field=models.FileField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='about',
            name='addition_file_button',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='contact',
            field=models.TextField(blank=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='about',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='about',
            name='cv_file_button',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_about',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_addition',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Additional skils title'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_contact',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Contact title'),
        ),
    ]
