# Generated by Django 5.1.2 on 2025-04-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generals', '0004_about_home_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='addition_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Addition image'),
        ),
        migrations.AddField(
            model_name='about',
            name='contact_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Contact image'),
        ),
    ]
